/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.toughdevs.school.popugtasktracker.tasks.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class Task extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4102557680758703560L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Task\",\"namespace\":\"com.toughdevs.school.popugtasktracker.tasks.schema\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"public_id\",\"type\":\"string\",\"doc\":\"The double type is a double precision (64-bit) IEEE 754 floating-point number.\"},{\"name\":\"description\",\"type\":\"string\",\"doc\":\"The string is a unicode character sequence.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Task> ENCODER =
      new BinaryMessageEncoder<Task>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Task> DECODER =
      new BinaryMessageDecoder<Task>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Task> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Task> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Task>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Task to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Task from a ByteBuffer. */
  public static Task fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The double type is a double precision (64-bit) IEEE 754 floating-point number. */
  @Deprecated public java.lang.CharSequence public_id;
  /** The string is a unicode character sequence. */
  @Deprecated public java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Task() {}

  /**
   * All-args constructor.
   * @param public_id The double type is a double precision (64-bit) IEEE 754 floating-point number.
   * @param description The string is a unicode character sequence.
   */
  public Task(java.lang.CharSequence public_id, java.lang.CharSequence description) {
    this.public_id = public_id;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return public_id;
    case 1: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: public_id = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'public_id' field.
   * @return The double type is a double precision (64-bit) IEEE 754 floating-point number.
   */
  public java.lang.CharSequence getPublicId() {
    return public_id;
  }

  /**
   * Sets the value of the 'public_id' field.
   * The double type is a double precision (64-bit) IEEE 754 floating-point number.
   * @param value the value to set.
   */
  public void setPublicId(java.lang.CharSequence value) {
    this.public_id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The string is a unicode character sequence.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * The string is a unicode character sequence.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Creates a new Task RecordBuilder.
   * @return A new Task RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder newBuilder() {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder();
  }

  /**
   * Creates a new Task RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Task RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder newBuilder(com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder other) {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder(other);
  }

  /**
   * Creates a new Task RecordBuilder by copying an existing Task instance.
   * @param other The existing instance to copy.
   * @return A new Task RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder newBuilder(com.toughdevs.school.popugtasktracker.tasks.schema.Task other) {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder(other);
  }

  /**
   * RecordBuilder for Task instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Task>
    implements org.apache.avro.data.RecordBuilder<Task> {

    /** The double type is a double precision (64-bit) IEEE 754 floating-point number. */
    private java.lang.CharSequence public_id;
    /** The string is a unicode character sequence. */
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.public_id)) {
        this.public_id = data().deepCopy(fields()[0].schema(), other.public_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Task instance
     * @param other The existing instance to copy.
     */
    private Builder(com.toughdevs.school.popugtasktracker.tasks.schema.Task other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.public_id)) {
        this.public_id = data().deepCopy(fields()[0].schema(), other.public_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'public_id' field.
      * The double type is a double precision (64-bit) IEEE 754 floating-point number.
      * @return The value.
      */
    public java.lang.CharSequence getPublicId() {
      return public_id;
    }

    /**
      * Sets the value of the 'public_id' field.
      * The double type is a double precision (64-bit) IEEE 754 floating-point number.
      * @param value The value of 'public_id'.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder setPublicId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.public_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'public_id' field has been set.
      * The double type is a double precision (64-bit) IEEE 754 floating-point number.
      * @return True if the 'public_id' field has been set, false otherwise.
      */
    public boolean hasPublicId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'public_id' field.
      * The double type is a double precision (64-bit) IEEE 754 floating-point number.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder clearPublicId() {
      public_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * The string is a unicode character sequence.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * The string is a unicode character sequence.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * The string is a unicode character sequence.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * The string is a unicode character sequence.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Task build() {
      try {
        Task record = new Task();
        record.public_id = fieldSetFlags()[0] ? this.public_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Task>
    WRITER$ = (org.apache.avro.io.DatumWriter<Task>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Task>
    READER$ = (org.apache.avro.io.DatumReader<Task>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
