/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.toughdevs.school.popugtasktracker.tasks.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Task_v1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2950246690992906384L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Task_v1\",\"namespace\":\"com.toughdevs.school.popugtasktracker.tasks.schema\",\"fields\":[{\"name\":\"public_id\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Task_v1> ENCODER =
      new BinaryMessageEncoder<Task_v1>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Task_v1> DECODER =
      new BinaryMessageDecoder<Task_v1>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Task_v1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Task_v1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Task_v1>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Task_v1 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Task_v1 from a ByteBuffer. */
  public static Task_v1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence public_id;
  @Deprecated public java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Task_v1() {}

  /**
   * All-args constructor.
   * @param public_id The new value for public_id
   * @param description The new value for description
   */
  public Task_v1(java.lang.CharSequence public_id, java.lang.CharSequence description) {
    this.public_id = public_id;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return public_id;
    case 1: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: public_id = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'public_id' field.
   * @return The value of the 'public_id' field.
   */
  public java.lang.CharSequence getPublicId() {
    return public_id;
  }

  /**
   * Sets the value of the 'public_id' field.
   * @param value the value to set.
   */
  public void setPublicId(java.lang.CharSequence value) {
    this.public_id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Creates a new Task_v1 RecordBuilder.
   * @return A new Task_v1 RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder newBuilder() {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder();
  }

  /**
   * Creates a new Task_v1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Task_v1 RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder newBuilder(com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder other) {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder(other);
  }

  /**
   * Creates a new Task_v1 RecordBuilder by copying an existing Task_v1 instance.
   * @param other The existing instance to copy.
   * @return A new Task_v1 RecordBuilder
   */
  public static com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder newBuilder(com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1 other) {
    return new com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder(other);
  }

  /**
   * RecordBuilder for Task_v1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Task_v1>
    implements org.apache.avro.data.RecordBuilder<Task_v1> {

    private java.lang.CharSequence public_id;
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.public_id)) {
        this.public_id = data().deepCopy(fields()[0].schema(), other.public_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Task_v1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.public_id)) {
        this.public_id = data().deepCopy(fields()[0].schema(), other.public_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'public_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublicId() {
      return public_id;
    }

    /**
      * Sets the value of the 'public_id' field.
      * @param value The value of 'public_id'.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder setPublicId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.public_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'public_id' field has been set.
      * @return True if the 'public_id' field has been set, false otherwise.
      */
    public boolean hasPublicId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'public_id' field.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder clearPublicId() {
      public_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.toughdevs.school.popugtasktracker.tasks.schema.Task_v1.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Task_v1 build() {
      try {
        Task_v1 record = new Task_v1();
        record.public_id = fieldSetFlags()[0] ? this.public_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Task_v1>
    WRITER$ = (org.apache.avro.io.DatumWriter<Task_v1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Task_v1>
    READER$ = (org.apache.avro.io.DatumReader<Task_v1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
